### ISSUE TITLE
Task #1

### ISSUE THREAD

**Issue by siarhei-birych** [anastasiakoroto/LX_Task_1#1]
1. Functionality is hard to support and extend. Try to implement the same logic using Classes and OOP based on SOLID principles.
2. Var and methods names should represent the business value of the object.
3. The time complexity of this solution is O(n * m), but it can be reduced to O(n + m).
4.  It's better to keep logic in separate modules
5. It's better to use arg parser
6. dict method setdefault could be used in _add_student_to_room

**Comment by anastasiakoroto** [comment]
Understood, I’ll fix it.

**Comment by anastasiakoroto** [comment]
Corrected
